FROM nginx:latest
COPY index.html /usr/share/nginx/html/index.html
COPY main2.js /usr/share/nginx/html/main2.js
COPY marker.png /usr/share/nginx/html/marker.png
COPY marker2.png /usr/share/nginx/html/marker2.png
COPY tabledraw.js /usr/share/nginx/html/tabledraw.js
ADD /style/ /usr/share/nginx/html/style
ADD /leaflet/ /usr/share/nginx/html/leaflet
ADD /node_modules/ /usr/share/nginx/html/node_modules
#ADD /leaflet/ /usr/share/nginx/html/leaflet
ADD /Leaflettiles/ /usr/share/nginx/html/Leaflettiles